apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: catalog-service
  name: catalog-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: catalog-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: catalog-service
    spec:
      containers:
        - image: chibilibs/catalog-service
          name: catalog-service
          env:
            - name: TMDB_API_KEY
              valueFrom:
                configMapKeyRef:
                  name: secrets
                  key: TMDB_API_KEY
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: catalog-service
  labels:
    app: catalog-service
spec:
  selector:
    app: catalog-service
  ports:
    - protocol: TCP
      port: 50052
      targetPort: 50052
  type:
    ClusterIP
