apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: flaresolverr
  name: flaresolverr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flaresolverr
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: flaresolverr
    spec:
      containers:
        - name: flaresolverr
          image: ghcr.io/flaresolverr/flaresolverr:latest
          env:
            - name: LOG_LEVEL
              value: "info"
          ports:
            - containerPort: 8191
              name: http-flaresolv
          resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: flaresolverr-service
spec:
  selector:
    app: flaresolverr
  ports:
    - protocol: TCP
      port: 8191
      targetPort: 8191
  type: ClusterIP
