apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: streaming-service
  name: streaming-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streaming-service
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: streaming-service
    spec:
      containers:
        - image: chibilibs/streaming-service
          name: streaming-service
          resources: {}
status: {}
