// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: catalog.proto

package catalog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetTrendingMoviesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingMoviesRequest) Reset() {
	*x = GetTrendingMoviesRequest{}
	mi := &file_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingMoviesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingMoviesRequest) ProtoMessage() {}

func (x *GetTrendingMoviesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingMoviesRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingMoviesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{0}
}

type GetTrendingMoviesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Movies        []*Movies              `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingMoviesResponse) Reset() {
	*x = GetTrendingMoviesResponse{}
	mi := &file_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingMoviesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingMoviesResponse) ProtoMessage() {}

func (x *GetTrendingMoviesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingMoviesResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingMoviesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *GetTrendingMoviesResponse) GetMovies() []*Movies {
	if x != nil {
		return x.Movies
	}
	return nil
}

type GetTrendingTVShowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingTVShowsRequest) Reset() {
	*x = GetTrendingTVShowsRequest{}
	mi := &file_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingTVShowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingTVShowsRequest) ProtoMessage() {}

func (x *GetTrendingTVShowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingTVShowsRequest.ProtoReflect.Descriptor instead.
func (*GetTrendingTVShowsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{2}
}

type GetTrendingTVShowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TvShows       []*TVShows             `protobuf:"bytes,1,rep,name=tv_shows,json=tvShows,proto3" json:"tv_shows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTrendingTVShowsResponse) Reset() {
	*x = GetTrendingTVShowsResponse{}
	mi := &file_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTrendingTVShowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTrendingTVShowsResponse) ProtoMessage() {}

func (x *GetTrendingTVShowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTrendingTVShowsResponse.ProtoReflect.Descriptor instead.
func (*GetTrendingTVShowsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *GetTrendingTVShowsResponse) GetTvShows() []*TVShows {
	if x != nil {
		return x.TvShows
	}
	return nil
}

type Movies struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	GenreIds      []int64                `protobuf:"varint,3,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Movies) Reset() {
	*x = Movies{}
	mi := &file_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Movies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Movies) ProtoMessage() {}

func (x *Movies) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Movies.ProtoReflect.Descriptor instead.
func (*Movies) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *Movies) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Movies) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Movies) GetGenreIds() []int64 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *Movies) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

type TVShows struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	GenreIds      []int64                `protobuf:"varint,3,rep,packed,name=genre_ids,json=genreIds,proto3" json:"genre_ids,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,4,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TVShows) Reset() {
	*x = TVShows{}
	mi := &file_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TVShows) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TVShows) ProtoMessage() {}

func (x *TVShows) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TVShows.ProtoReflect.Descriptor instead.
func (*TVShows) Descriptor() ([]byte, []int) {
	return file_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *TVShows) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TVShows) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *TVShows) GetGenreIds() []int64 {
	if x != nil {
		return x.GenreIds
	}
	return nil
}

func (x *TVShows) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

var File_catalog_proto protoreflect.FileDescriptor

const file_catalog_proto_rawDesc = "" +
	"\n" +
	"\rcatalog.proto\x12\acatalog\"\x1a\n" +
	"\x18GetTrendingMoviesRequest\"D\n" +
	"\x19GetTrendingMoviesResponse\x12'\n" +
	"\x06movies\x18\x01 \x03(\v2\x0f.catalog.MoviesR\x06movies\"\x1b\n" +
	"\x19GetTrendingTVShowsRequest\"I\n" +
	"\x1aGetTrendingTVShowsResponse\x12+\n" +
	"\btv_shows\x18\x01 \x03(\v2\x10.catalog.TVShowsR\atvShows\"n\n" +
	"\x06Movies\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tgenre_ids\x18\x03 \x03(\x03R\bgenreIds\x12!\n" +
	"\frelease_date\x18\x04 \x01(\tR\vreleaseDate\"o\n" +
	"\aTVShows\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x1b\n" +
	"\tgenre_ids\x18\x03 \x03(\x03R\bgenreIds\x12!\n" +
	"\frelease_date\x18\x04 \x01(\tR\vreleaseDate2\xcb\x01\n" +
	"\x0eCatalogService\x12Z\n" +
	"\x11GetTrendingMovies\x12!.catalog.GetTrendingMoviesRequest\x1a\".catalog.GetTrendingMoviesResponse\x12]\n" +
	"\x12GetTrendingTVShows\x12\".catalog.GetTrendingTVShowsRequest\x1a#.catalog.GetTrendingTVShowsResponseB\x1eZ\x1cshared/proto/catalog;catalogb\x06proto3"

var (
	file_catalog_proto_rawDescOnce sync.Once
	file_catalog_proto_rawDescData []byte
)

func file_catalog_proto_rawDescGZIP() []byte {
	file_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)))
	})
	return file_catalog_proto_rawDescData
}

var file_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_catalog_proto_goTypes = []any{
	(*GetTrendingMoviesRequest)(nil),   // 0: catalog.GetTrendingMoviesRequest
	(*GetTrendingMoviesResponse)(nil),  // 1: catalog.GetTrendingMoviesResponse
	(*GetTrendingTVShowsRequest)(nil),  // 2: catalog.GetTrendingTVShowsRequest
	(*GetTrendingTVShowsResponse)(nil), // 3: catalog.GetTrendingTVShowsResponse
	(*Movies)(nil),                     // 4: catalog.Movies
	(*TVShows)(nil),                    // 5: catalog.TVShows
}
var file_catalog_proto_depIdxs = []int32{
	4, // 0: catalog.GetTrendingMoviesResponse.movies:type_name -> catalog.Movies
	5, // 1: catalog.GetTrendingTVShowsResponse.tv_shows:type_name -> catalog.TVShows
	0, // 2: catalog.CatalogService.GetTrendingMovies:input_type -> catalog.GetTrendingMoviesRequest
	2, // 3: catalog.CatalogService.GetTrendingTVShows:input_type -> catalog.GetTrendingTVShowsRequest
	1, // 4: catalog.CatalogService.GetTrendingMovies:output_type -> catalog.GetTrendingMoviesResponse
	3, // 5: catalog.CatalogService.GetTrendingTVShows:output_type -> catalog.GetTrendingTVShowsResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_catalog_proto_init() }
func file_catalog_proto_init() {
	if File_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_proto_rawDesc), len(file_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_proto_msgTypes,
	}.Build()
	File_catalog_proto = out.File
	file_catalog_proto_goTypes = nil
	file_catalog_proto_depIdxs = nil
}
