// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.4
// source: indexer.proto

package indexer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetMovieMagneticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,2,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieMagneticRequest) Reset() {
	*x = GetMovieMagneticRequest{}
	mi := &file_indexer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieMagneticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieMagneticRequest) ProtoMessage() {}

func (x *GetMovieMagneticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieMagneticRequest.ProtoReflect.Descriptor instead.
func (*GetMovieMagneticRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{0}
}

func (x *GetMovieMagneticRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetMovieMagneticRequest) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

type GetMovieMagneticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*Torrents            `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMovieMagneticResponse) Reset() {
	*x = GetMovieMagneticResponse{}
	mi := &file_indexer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMovieMagneticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMovieMagneticResponse) ProtoMessage() {}

func (x *GetMovieMagneticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMovieMagneticResponse.ProtoReflect.Descriptor instead.
func (*GetMovieMagneticResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{1}
}

func (x *GetMovieMagneticResponse) GetTorrents() []*Torrents {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type GetTVShowMagneticRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ReleaseDate   string                 `protobuf:"bytes,2,opt,name=release_date,json=releaseDate,proto3" json:"release_date,omitempty"`
	Episode       int32                  `protobuf:"varint,3,opt,name=episode,proto3" json:"episode,omitempty"`
	Season        int32                  `protobuf:"varint,4,opt,name=season,proto3" json:"season,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTVShowMagneticRequest) Reset() {
	*x = GetTVShowMagneticRequest{}
	mi := &file_indexer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTVShowMagneticRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTVShowMagneticRequest) ProtoMessage() {}

func (x *GetTVShowMagneticRequest) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTVShowMagneticRequest.ProtoReflect.Descriptor instead.
func (*GetTVShowMagneticRequest) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{2}
}

func (x *GetTVShowMagneticRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetTVShowMagneticRequest) GetReleaseDate() string {
	if x != nil {
		return x.ReleaseDate
	}
	return ""
}

func (x *GetTVShowMagneticRequest) GetEpisode() int32 {
	if x != nil {
		return x.Episode
	}
	return 0
}

func (x *GetTVShowMagneticRequest) GetSeason() int32 {
	if x != nil {
		return x.Season
	}
	return 0
}

type GetTVShowMagneticResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Torrents      []*Torrents            `protobuf:"bytes,1,rep,name=torrents,proto3" json:"torrents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetTVShowMagneticResponse) Reset() {
	*x = GetTVShowMagneticResponse{}
	mi := &file_indexer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetTVShowMagneticResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetTVShowMagneticResponse) ProtoMessage() {}

func (x *GetTVShowMagneticResponse) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetTVShowMagneticResponse.ProtoReflect.Descriptor instead.
func (*GetTVShowMagneticResponse) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{3}
}

func (x *GetTVShowMagneticResponse) GetTorrents() []*Torrents {
	if x != nil {
		return x.Torrents
	}
	return nil
}

type Torrents struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MagneticUri   string                 `protobuf:"bytes,1,opt,name=magnetic_uri,json=magneticUri,proto3" json:"magnetic_uri,omitempty"`
	Size          uint32                 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	Seeders       uint32                 `protobuf:"varint,3,opt,name=seeders,proto3" json:"seeders,omitempty"`
	Tracker       string                 `protobuf:"bytes,4,opt,name=tracker,proto3" json:"tracker,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Torrents) Reset() {
	*x = Torrents{}
	mi := &file_indexer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Torrents) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Torrents) ProtoMessage() {}

func (x *Torrents) ProtoReflect() protoreflect.Message {
	mi := &file_indexer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Torrents.ProtoReflect.Descriptor instead.
func (*Torrents) Descriptor() ([]byte, []int) {
	return file_indexer_proto_rawDescGZIP(), []int{4}
}

func (x *Torrents) GetMagneticUri() string {
	if x != nil {
		return x.MagneticUri
	}
	return ""
}

func (x *Torrents) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *Torrents) GetSeeders() uint32 {
	if x != nil {
		return x.Seeders
	}
	return 0
}

func (x *Torrents) GetTracker() string {
	if x != nil {
		return x.Tracker
	}
	return ""
}

var File_indexer_proto protoreflect.FileDescriptor

const file_indexer_proto_rawDesc = "" +
	"\n" +
	"\rindexer.proto\x12\acatalog\"P\n" +
	"\x17GetMovieMagneticRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\frelease_date\x18\x02 \x01(\tR\vreleaseDate\"I\n" +
	"\x18GetMovieMagneticResponse\x12-\n" +
	"\btorrents\x18\x01 \x03(\v2\x11.catalog.TorrentsR\btorrents\"\x83\x01\n" +
	"\x18GetTVShowMagneticRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\frelease_date\x18\x02 \x01(\tR\vreleaseDate\x12\x18\n" +
	"\aepisode\x18\x03 \x01(\x05R\aepisode\x12\x16\n" +
	"\x06season\x18\x04 \x01(\x05R\x06season\"J\n" +
	"\x19GetTVShowMagneticResponse\x12-\n" +
	"\btorrents\x18\x01 \x03(\v2\x11.catalog.TorrentsR\btorrents\"u\n" +
	"\bTorrents\x12!\n" +
	"\fmagnetic_uri\x18\x01 \x01(\tR\vmagneticUri\x12\x12\n" +
	"\x04size\x18\x02 \x01(\rR\x04size\x12\x18\n" +
	"\aseeders\x18\x03 \x01(\rR\aseeders\x12\x18\n" +
	"\atracker\x18\x04 \x01(\tR\atracker2\xc5\x01\n" +
	"\x0eIndexerService\x12W\n" +
	"\x10GetMovieMagnetic\x12 .catalog.GetMovieMagneticRequest\x1a!.catalog.GetMovieMagneticResponse\x12Z\n" +
	"\x11GetTVShowMagnetic\x12!.catalog.GetTVShowMagneticRequest\x1a\".catalog.GetTVShowMagneticResponseB\x1eZ\x1cshared/proto/indexer;indexerb\x06proto3"

var (
	file_indexer_proto_rawDescOnce sync.Once
	file_indexer_proto_rawDescData []byte
)

func file_indexer_proto_rawDescGZIP() []byte {
	file_indexer_proto_rawDescOnce.Do(func() {
		file_indexer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)))
	})
	return file_indexer_proto_rawDescData
}

var file_indexer_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_indexer_proto_goTypes = []any{
	(*GetMovieMagneticRequest)(nil),   // 0: catalog.GetMovieMagneticRequest
	(*GetMovieMagneticResponse)(nil),  // 1: catalog.GetMovieMagneticResponse
	(*GetTVShowMagneticRequest)(nil),  // 2: catalog.GetTVShowMagneticRequest
	(*GetTVShowMagneticResponse)(nil), // 3: catalog.GetTVShowMagneticResponse
	(*Torrents)(nil),                  // 4: catalog.Torrents
}
var file_indexer_proto_depIdxs = []int32{
	4, // 0: catalog.GetMovieMagneticResponse.torrents:type_name -> catalog.Torrents
	4, // 1: catalog.GetTVShowMagneticResponse.torrents:type_name -> catalog.Torrents
	0, // 2: catalog.IndexerService.GetMovieMagnetic:input_type -> catalog.GetMovieMagneticRequest
	2, // 3: catalog.IndexerService.GetTVShowMagnetic:input_type -> catalog.GetTVShowMagneticRequest
	1, // 4: catalog.IndexerService.GetMovieMagnetic:output_type -> catalog.GetMovieMagneticResponse
	3, // 5: catalog.IndexerService.GetTVShowMagnetic:output_type -> catalog.GetTVShowMagneticResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_indexer_proto_init() }
func file_indexer_proto_init() {
	if File_indexer_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_indexer_proto_rawDesc), len(file_indexer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_indexer_proto_goTypes,
		DependencyIndexes: file_indexer_proto_depIdxs,
		MessageInfos:      file_indexer_proto_msgTypes,
	}.Build()
	File_indexer_proto = out.File
	file_indexer_proto_goTypes = nil
	file_indexer_proto_depIdxs = nil
}
